# Generated by Django 5.0.4 on 2024-10-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('expired', 'Expired')], max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='main.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
