# Generated by Django 5.0.4 on 2024-11-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('happening', 'Happening'), ('upcoming', 'Upcoming'), ('expired', 'Expired')], max_length=20),
        ),
    ]
