# Generated by Django 5.0.4 on 2024-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_eventgallery_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('happening', 'Happening'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], max_length=20),
        ),
    ]
