# Generated by Django 5.0.4 on 2024-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_event_day_remove_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_gallery_images/'),
        ),
    ]
